test_that("scales functions works", {
  fill_scale <- scale_fill_rss_c(name = "signif_seq")
  expect_equal(fill_scale$is_discrete(), FALSE)
  fill_scale <- scale_fill_rss_c(name = "signif_seq", legend_title = "New Title")
  expect_equal(fill_scale$is_discrete(), FALSE)
  expect_error(scale_fill_rss_c(name = "signif_seq"))
  expect_error(scale_fill_rss_c(name = "signif_seq", direction = 0))

  fill_scale <- scale_fill_rss_d(name = "signif_qual")
  expect_equal(fill_scale$is_discrete(), TRUE)
  fill_scale <- scale_fill_rss_d(name = "signif_qual", legend_title = "New Title")
  expect_equal(fill_scale$is_discrete(), TRUE)
  fill_scale <- scale_fill_rss_d(name = "signif_qual", direction = -1)
  expect_equal(fill_scale$is_discrete(), TRUE)
  expect_error(scale_fill_rss_d(name = "new_name"))
  expect_error(scale_fill_rss_d(name = "signif_qual", direction = 0))

  colour_scale <- scale_colour_rss_c(name = "signif_seq")
  expect_equal(colour_scale$is_discrete(), FALSE)
  colour_scale <- scale_colour_rss_c(name = "signif_seq", legend_title = "New Title")
  expect_equal(colour_scale$is_discrete(), FALSE)
  expect_error(scale_colour_rss_c(name = "signif_sequential"))
  expect_error(scale_colour_rss_c(name = "signif_seq", direction = 0))

  colour_scale <- scale_color_rss_c(name = "signif_seq")
  expect_equal(colour_scale$is_discrete(), FALSE)
  colour_scale <- scale_color_rss_c(name = "signif_seq", legend_title = "New Title")
  expect_equal(colour_scale$is_discrete(), FALSE)
  expect_error(scale_color_rss_c(name = "signif_sequential"))
  expect_error(scale_color_rss_c(name = "signif_seq", direction = 0))

  colour_scale <- scale_colour_rss_d(name = "signif_qual")
  expect_equal(colour_scale$is_discrete(), TRUE)
  colour_scale <- scale_colour_rss_d(name = "signif_qual", legend_title = "New Title")
  expect_equal(colour_scale$is_discrete(), TRUE)
  colour_scale <- scale_colour_rss_d(name = "signif_qual", direction = -1)
  expect_equal(colour_scale$is_discrete(), TRUE)
  expect_error(scale_colour_rss_d(name = "signif_qualit"))
  expect_error(scale_colour_rss_d(name = "signif_qual", direction = 0))

  colour_scale <- scale_color_rss_d(name = "signif_qual")
  expect_equal(colour_scale$is_discrete(), TRUE)
  colour_scale <- scale_color_rss_d(name = "signif_qual", legend_title = "New Title")
  expect_equal(colour_scale$is_discrete(), TRUE)
  colour_scale <- scale_color_rss_d(name = "signif_qual", direction = -1)
  expect_equal(colour_scale$is_discrete(), TRUE)
  expect_error(scale_color_rss_d(name = "signif_qualit"))
  expect_error(scale_color_rss_d(name = "signif_qual", direction = 0))
})
